dubbo:
  application:
    name: dubbo_provider
  registry:
    address: redis://localhost:6379
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: top.durandal.service
spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/cook?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: 123
mybatis:
  configuration:
    map-underscore-to-camel-case: true