server:
  port: 8888
dubbo:
  application:
    name: annotation-consumer
  registry:
    address: redis://127.0.0.1:6379
  consumer:
    timeout: 3000
spring:
  security:
    user:
      name: user
      password: 123
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/cook?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true